
--Remplace police forces codes by their labels

UPDATE UK_accidents.dbo.accidents
SET police_force = CASE WHEN police_force = 1  THEN REPLACE(police_force, 1 , 'Metropolitan Police') 
                        WHEN police_force = 3  THEN REPLACE(police_force, 3 , 'Cumbria') 
	                    WHEN police_force = 4  THEN REPLACE(police_force, 4 , 'Lancashire') 
	                    WHEN police_force = 5  THEN REPLACE(police_force, 5 , 'Merseyside') 
	                    WHEN police_force = 6  THEN REPLACE(police_force, 6 , 'Greater Manchester') 
	                    WHEN police_force = 7  THEN REPLACE(police_force, 7 , 'Cheshire') 
	                    WHEN police_force = 10 THEN REPLACE(police_force, 10, 'Northumbria')
			            WHEN police_force = 11 THEN REPLACE(police_force, 11, 'Durham') 
			            WHEN police_force = 12 THEN REPLACE(police_force, 12, 'North Yorkshire') 
			            WHEN police_force = 13 THEN REPLACE(police_force, 13, 'West Yorkshire') 
			            WHEN police_force = 14 THEN REPLACE(police_force, 14, 'South Yorkshire')
			            WHEN police_force = 16 THEN REPLACE(police_force, 16, 'Humberside') 
			            WHEN police_force = 17 THEN REPLACE(police_force, 17, 'Cleveland') 
			            WHEN police_force = 20 THEN REPLACE(police_force, 20, 'West Midlands') 
			            WHEN police_force = 21 THEN REPLACE(police_force, 21, 'Staffordshire') 
			            WHEN police_force = 22 THEN REPLACE(police_force, 22, 'West Mercia') 
			            WHEN police_force = 23 THEN REPLACE(police_force, 23, 'Warwickshire') 
			            WHEN police_force = 30 THEN REPLACE(police_force, 30, 'Derbyshire')
			            WHEN police_force = 31 THEN REPLACE(police_force, 31, 'Nottinghamshire') 
			            WHEN police_force = 32 THEN REPLACE(police_force, 32, 'Lincolnshire') 
			            WHEN police_force = 33 THEN REPLACE(police_force, 33, 'Leicestershire') 
			            WHEN police_force = 34 THEN REPLACE(police_force, 34, 'Northamptonshire') 
			            WHEN police_force = 35 THEN REPLACE(police_force, 35, 'Cambridgeshire') 
			            WHEN police_force = 36 THEN REPLACE(police_force, 36, 'Norfolk') 
			            WHEN police_force = 37 THEN REPLACE(police_force, 37, 'Suffolk')
			            WHEN police_force = 40 THEN REPLACE(police_force, 40, 'Bedfordshire') 
			            WHEN police_force = 41 THEN REPLACE(police_force, 41, 'Hertfordshire') 
			            WHEN police_force = 42 THEN REPLACE(police_force, 42, 'Essex') 
			            WHEN police_force = 43 THEN REPLACE(police_force, 43, 'Thames Valley') 
			            WHEN police_force = 44 THEN REPLACE(police_force, 44, 'Hampshire') 
			            WHEN police_force = 45 THEN REPLACE(police_force, 45, 'Surrey') 
			            WHEN police_force = 46 THEN REPLACE(police_force, 46, 'Kent')
			            WHEN police_force = 47 THEN REPLACE(police_force, 47, 'Sussex') 
			            WHEN police_force = 48 THEN REPLACE(police_force, 48, 'City of London') 
			            WHEN police_force = 50 THEN REPLACE(police_force, 50, 'Devon and Cornwall') 
			            WHEN police_force = 52 THEN REPLACE(police_force, 52, 'Avon and Somerset') 
			            WHEN police_force = 53 THEN REPLACE(police_force, 53, 'Gloucestershire') 
			            WHEN police_force = 54 THEN REPLACE(police_force, 54, 'Wiltshire') 
			            WHEN police_force = 55 THEN REPLACE(police_force, 55, 'Dorset')
			            WHEN police_force = 60 THEN REPLACE(police_force, 60, 'North Wales') 
			            WHEN police_force = 61 THEN REPLACE(police_force, 61, 'Gwent') 
			            WHEN police_force = 62 THEN REPLACE(police_force, 62, 'South Wales')
			            WHEN police_force = 63 THEN REPLACE(police_force, 63, 'Dyfed-Powys') 
			            WHEN police_force = 91 THEN REPLACE(police_force, 91, 'Northern')
			            WHEN police_force = 92 THEN REPLACE(police_force, 92, 'Grampian') 
			            WHEN police_force = 93 THEN REPLACE(police_force, 93, 'Tayside') 
			            WHEN police_force = 94 THEN REPLACE(police_force, 94, 'Fife') 
			            WHEN police_force = 95 THEN REPLACE(police_force, 95, 'Lothian and Borders') 
			            WHEN police_force = 96 THEN REPLACE(police_force, 96, 'Central') 
			            WHEN police_force = 97 THEN REPLACE(police_force, 97, 'Strathclyde') 
			            WHEN police_force = 98 THEN REPLACE(police_force, 98, 'Dumfries and Galloway')
			            WHEN police_force = 99 THEN REPLACE(police_force, 99, 'Police Scotland') 
	                    ELSE NULL 
						END 



					    
